namespace: my-namespace
nginx:
  image: my-nginx-image:latest
  replicas: 2
  ssh_port: 22
  service_port: 80
  service_type: NodePort
mariadb:
  host: mariadb-host
  port: 3306
  username: db_user
  password: db_password
  database: my_database
network:
  name: my-network
  ip_range: 192.168.0.0/24
  subnet: 192.168.0.0/24
  gateway: 192.168.0.1
urls:
  nginx: http://nginx-service:80
  mariadb: mysql://{{ mariadb.username }}:{{ mariadb.password }}@{{ mariadb.host }}:{{ mariadb.port }}/{{ mariadb.database }}